language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
install: "pip install -r requirements/test.txt"
script:
  - "python tests.py"
  - "pep8 . --max-line-length=100"
branches:
  only:
    - master
    - develop
